alter sequence gender_id_seq restart;
alter sequence filmcgt_id_seq restart;
alter sequence acttype_id_seq restart;
alter sequence plateauctg_id_seq restart;
alter sequence acteur_id_seq restart;
alter sequence acteurdispo_id_seq restart;
alter sequence plateau_id_seq restart;
alter sequence plateaudispo_id_seq restart;
alter sequence film_id_seq restart;
alter sequence scene_id_seq restart;
alter sequence emotion_id_seq restart;
alter sequence act_id_seq restart;
alter sequence scenestatus_id_seq restart;
alter sequence planning_id_seq restart;
alter sequence personne_id_seq restart;

delete from planning where true;
delete from act where true;
delete from scene where true;
delete from SceneStatus where true;
delete from FILM where true;
delete from Plateaudispo where true;
delete from Plateau where true;
delete from acteurdispo where true;
delete from Acteur where true;
delete from Plateauctg where true;
delete from Acttype where true;
delete from Filmctg where true;
delete from Emotion where true;
delete from Gender where true;
